services:
  app:
    build:
      context: .
    container_name: giftlist-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: giftlist-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: giftlist-db
    environment:
      POSTGRES_DB: GiftList
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vite:
    image: node:20
    container_name: giftlist-vite
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host

volumes:
  pgdata:
  node_modules:
